#
#       ▄▄▌ ▐ ▄▌ ▄▄▄· ▄▄▌  ▄▄▌  ▄▄▄▄▄ ▄▄▄· ▄ •▄ ▄▄▄ .▄▄▄  
#       ██· █▌▐█▐█ ▀█ ██•  ██•  •██  ▐█ ▀█ █▌▄▌▪▀▄.▀·▀▄ █·
#       ██▪▐█▐▐▌▄█▀▀█ ██▪  ██▪   ▐█.▪▄█▀▀█ ▐▀▀▄·▐▀▀▪▄▐▀▀▄ 
#       ▐█▌██▐█▌▐█ ▪▐▌▐█▌▐▌▐█▌▐▌ ▐█▌·▐█ ▪▐▌▐█.█▌▐█▄▄▌▐█•█▌
#        ▀▀▀▀ ▀▪ ▀  ▀ .▀▀▀ .▀▀▀  ▀▀▀  ▀  ▀ ·▀  ▀ ▀▀▀ .▀  ▀
#                        Configuration File
#
#####################################################################
###########################  Base Config  ###########################
#####################################################################

[Base] # do not change 
base = "https://walltaker.joi.how/links/"

#####################################################################
########################  Your Link Config  #########################
#####################################################################

[Feed] # the link number to watch
feed = 0 # placeholder; please replace with your number, otherwise this will error out

#####################################################################
########################  Other Preferences  ########################
#####################################################################

[Preferences]
# interval: how many seconds to wait between check-ins. Recommended: 10 -- THIS IS DEPRECATED AS OF v2.1.0
interval = 10  # THIS IS DEPRECATED AS OF v2.1.0

# mode: whether to "crop" or "fit" the images. Defualt: "crop"
mode = "crop"

# discordPresence: whether or not to use Discord's Rich Presence to show you are running Walltaker. Defualt: false
discordPresence = false

# saveLocally: save sent wallpapers into local files Defualt: false
saveLocally = false

# notifications: alert you using system notifications when new wallpapers come in. Defualt: false
notifications = false
